### ISSUE TITLE
`incremental` mode not working in SQLServer as source when `update-key` has datetime data type

### ISSUE THREAD

**Issue by trung** [slingdata-io/sling-cli#366] opened 2024-08-22 17:16 UTC
## Issue Description

- Description of the issue: 

`incremental` mode not working for SQLServer as source

- Sling version (`sling --version`): 

1.2.15

- Operating System (`linux`, `mac`, `windows`): 

Linux

- Log Output (please run command with `-d`): 

```
2024-08-22 17:03:38 DBG select max("CreatedTimestamp") as max_val from "TargetTable"
2024-08-22 17:03:39 INF reading from source database
2024-08-22 17:03:39 DBG select * from "SourceTable" where "CreatedTimestamp" >= '2024-08-21 01:11:16.767000' order by "CreatedTimestamp"  asc offset 0 rows
2024-08-22 17:03:39 INF writing to target database [mode: incremental]
2024-08-22 17:03:39 DBG drop table if exists "TargetTable_tmp"
2024-08-22 17:03:39 DBG table "TargetTable_tmp" dropped
2024-08-22 17:03:39 DBG create table if not exists "TargetTable_tmp" ...<snip>...
2024-08-22 17:03:39 INF streaming data
2024-08-22 17:03:39 DBG select count(*) cnt from "TargetTable_tmp"
2024-08-22 17:03:39 WRN No data or records found in stream. Nothing to do. To allow Sling to create empty tables, set SLING_ALLOW_EMPTY=TRUE
2024-08-22 17:03:39 INF inserted 0 rows into "TargetTable" in 0 secs [0 r/s]
...<snip>...
```

`SourceTable.CreatedTimestamp` has type `datetime`.

When executing the query
```sql
select * from "SourceTable" where "CreatedTimestamp" >= '2024-08-21 01:11:16.767000' order by "CreatedTimestamp"  asc offset 0 rows
```
directly in the SQLServer, it returns an error:
```
Conversion failed when converting date and/or time from character string.
```

This is due to the `datetime` type in SQL Server has [a precision of 3.33 milliseconds](https://learn.microsoft.com/en-us/sql/t-sql/data-types/datetime-transact-sql?view=sql-server-ver16), which means it supports up to 3 decimal places for fractional seconds. However, the value provided in the query includes fractional seconds (.767000), which exceeds the precision of the `datetime` type in SQL Server.

**Comment by flarco** [comment] 2024-08-22 17:46
Interesting, thanks.

Can you confirm that sling is actually erroring when it runs `select * from "SourceTable" where "CreatedTimestamp" >= '2024-08-21 01:11:16.767000'...`? If not, that's a problem in itself.

Your log shows `No data or records found in stream. Nothing to do`, I didn't see an error (since it's snipped).

**Comment by trung** [comment] 2024-08-22 19:55
I only snip the create table content. Logs are in the same order as they appeared. 

> Can you confirm that sling is actually erroring when it runs select * from "SourceTable" where "CreatedTimestamp" >= '2024-08-21 01:11:16.767000'...? If not, that's a problem in itself.

Yeah, I don't see any error from Sling when this sql is executed.

**Comment by guaripete-github** [comment] 2024-08-23 18:28
My workaround was to use custom query to cast the incremental value datatype. For example:

```yaml
    sql: |
      SELECT * FROM {stream_name}
      WHERE CreatedTimestamp >= COALESCE(CAST({incremental_value} AS datetime2), '1900-01-01')
```

**Comment by trung** [comment] 2024-08-23 20:32
@guaripete-github thanks. `{incremental_value}` is gold. Don't see that in the list of global variables so I assume this is your discovery when skimming through the code.

@flarco could `{incremental_value}` be a global variable to use?

**Comment by flarco** [comment] 2024-08-23 22:18
@trung `incremental_value` is discussed [here](https://docs.slingdata.io/sling-cli/run/configuration#incremental-or-backfill-mode-with-custom-sql).
As far as being used as a global variable, not sure I understand, could you expand a bit on how/where you would use it? ATM it's only available in the custom SQL expression.

**Comment by flarco** [comment] 2024-08-26 22:37
Should be fixed in #357 . Closing

**Closed by flarco** 2024-08-26 22:37 UTC
Labels: bug

**Comment by guaripete-github** [comment] 2024-10-31 16:53
@flarco Looks like there is a regression since 1.2.21 release. Getting this error again.

**Comment by flarco** [comment] 2024-10-31 18:30
@guaripete-github could you share the column type of the source and target datetime column? is is `datetime2`?

**Comment by guaripete-github** [comment] 2024-12-09 14:45
@flarco the source column is `datetime`. Tested with both `datetime2(3)` and `datetime` in destination column, but same error. On either case, the incremental value in string (e.g. '2024-12-06 16:44:00.000000') is set with the equivalent of `datetime2(6)` and thus failing the implicit conversion to `datetime`. Conversion does not fail with '2024-12-06 16:44:00.000'.
