### ISSUE TITLE
Split `date` & `timestamp` Data Types

### ISSUE THREAD

**Issue by fabrice-etanchaud** [slingdata-io/sling-cli#210] opened 2024-03-10 17:01 UTC
Hi !
Testing 1.1.12, I found that native date columns are changed to general datetime columns leading to a timestamp in the target db :

https://github.com/slingdata-io/sling-cli/blob/2e4babad75071702717a963378132b23c5061263/core/dbio/database/templates/types_native_to_general.tsv#L90

Could they be mapped to date ?

Thank you !

**Comment by flarco** [comment] 2024-03-10 17:19
Yes, it was designed this way for simplicity, but it's a good time to look into splitting dates & timestamps.

**Comment by flarco** [comment] 2024-03-12 00:27
Done. `v1.1.14` should map dates correctly.
Closing.

**Closed by flarco** 2024-03-12 00:27 UTC
Labels: enhancement

**Comment by fabrice-etanchaud** [comment] 2024-03-12 09:16
Thank you @flarco, it's a great chance to see that sling is such an active project !

**Comment by TylerTollefson** [comment] 2024-04-09 17:42
Looks like this change introduced an issue when converting oracle date it is now being mapped as a generic type date, however Oracle "date" do include time components. So when an Oracle date is being mapped to bigquery date, that time component is lost...

**Comment by flarco** [comment] 2024-04-09 17:52
Interesting. So, in oracle `date` is the same as `datetime`?
For now, you can overrride the type with `source_options.colums: { "date_col": datetime }`

**Comment by TylerTollefson** [comment] 2024-04-09 19:01
Correct, which is why in the patch before v1.1.14 the mapping of the types worked. The override should work for now though, thanks!

**Comment by flarco** [comment] 2024-04-09 21:03
Thanks, will fix.

**Comment by TylerTollefson** [comment] 2024-04-23 15:24
> sling-cli/core/dbio/database/templates/types_native_to_general.tsv

Just wanted to circle back on this after I've had some more time to test in my env, the issue here is that there is no mapping for Oracle datetime anymore. When the override suggested above was in my replication yaml it failed the migration into BigQuery because it couldn't coerce from timestamp to datetime. Removing the override allows the migration to finish but we end up losing the time part of the datetime type.

**Comment by TylerTollefson** [comment] 2024-04-23 17:38
Theres no mapping for Oracle's datetime type, that what seems to be missing. If I understand correctly, we would need to have a datetime -> datetime for Oracle to BigQuery.

**Comment by TylerTollefson** [comment] 2024-04-23 17:45
Sure, I'll give that a try and let you know.
