### ISSUE TITLE
Use the low case db/table name for StarRocks target, but the generated CREATE TABLE STATEMENT use the uppper case databasename/table name.

### ISSUE THREAD

**Issue by MarkovWangRR** [slingdata-io/sling-cli#193] opened 2024-02-28 07:01 UTC
wangyouzhuo@markovwong file % sling run --src-conn EXTERNAL_SNOWFLAKE_SSB_100GB --src-stream 'SSB_SF100GCL.CUSTOMER' --tgt-conn CELERDATA_SAAS --tgt-object 'DB_SLING_TEST.CUSTOMER' --mode full-refresh

2:40PM INF connecting to source database (snowflake)
2:40PM INF connecting to target database (starrocks)
2:40PM INF reading from source database
2:40PM INF writing to target database [mode: full-refresh]
2:40PM INF execution failed

fatal:
~ Could not execute SQL

~ Error executing [tx: false] create table if not exists `db_sling_test`.`customer_tmp` (`c_custkey` bigint,
`c_name` varchar(65533),
`c_address` varchar(65533),
`c_city` varchar(65533),
`c_nation` varchar(65533),
`c_region` varchar(65533),
`c_phone` varchar(65533),
`c_mktsegment` varchar(65533),
`_sling_row_id` varchar(65533))  distributed by hash(`_sling_row_id`)
Error 1064 (HY000):  Getting analyzing error. Detail message: Unknown database 'db_sling_test'.

![截屏2024-02-28 14 53 44](https://github.com/slingdata-io/sling-cli/assets/101642945/01993477-9865-4ce4-ae41-18a5ecf70b26)

In fact, the database named DB_SLING_TEST is already existed in StarRocks. I think the root issue is that StarRocks is case sensitive.

**Comment by MarkovWangRR** [comment] 2024-02-28 07:07
When i use the lowcase db/table name for StarRocks, everything is OK. When i use the upcase db/table name, the generated SQL will be auto case into lowcase. 
I guess it's a known root case for the known issue. So i just raise a issue for it so i can observe the newest status about it.
My sling version is 1.1.8. 

Feel happy if you need more detail about it. Thank!

**Comment by flarco** [comment] 2024-02-28 10:37
Can you run with `-d` flag?

I am unable to reproduce: it does ``create schema `test1` ``

```
$ sling run --src-conn clickhouse  --src-stream plau.events --tgt-conn starrocks --tgt-object 'TEST1.EVENTS' -l 1000 -
d
024-02-28 07:30:24 INF connecting to source database (clickhouse)
2024-02-28 07:30:25 INF connecting to target database (starrocks)
2024-02-28 07:30:25 INF reading from source database
2024-02-28 07:30:25 DBG select * from (
  select * from `plau`.`events`
) as t limit ***
2024-02-28 07:30:25 INF writing to target database [mode: full-refresh]
2024-02-28 07:30:25 DBG create schema `test1`
2024-02-28 07:30:25 DBG drop table if exists `test1`.`events_tmp`
2024-02-28 07:30:25 DBG table `test1`.`events_tmp` dropped
2024-02-28 07:30:26 DBG create table if not exists `test1`.`events_tmp` (`name` varchar(65533), ......
```

**Comment by MarkovWangRR** [comment] 2024-02-28 11:16
wangyouzhuo@markovwong file % sling run --src-conn EXTERNAL_SNOWFLAKE_SSB_100GB --src-stream 'SSB_SF100GCL.CUSTOMER' --tgt-conn CELERDATA_SAAS --tgt-object 'DB_SLING_TEST.CUSTOMER' --mode full-refresh -d

2024-02-28 19:16:21 DBG Sling version: 1.1.8 (darwin arm64)
2024-02-28 19:16:21 DBG type is db-db
2024-02-28 19:16:21 DBG using source options: {"empty_as_null":true,"null_if":"NULL","datetime_format":"AUTO","max_decimals":-1,"transforms":["parse_bit"]}
2024-02-28 19:16:21 DBG using target options: {"datetime_format":"auto","max_decimals":-1,"use_bulk":true,"add_new_columns":true,"column_casing":"source"}
2024-02-28 19:16:21 INF connecting to source database (snowflake)
2024-02-28 19:16:26 INF connecting to target database (starrocks)
2024-02-28 19:16:29 INF reading from source database
2024-02-28 19:16:30 DBG select * from "SSB_SF100GCL"."CUSTOMER"
2024-02-28 19:16:36 INF writing to target database [mode: full-refresh]
2024-02-28 19:16:36 DBG drop table if exists `db_sling_test`.`customer_tmp`
2024-02-28 19:16:37 DBG table `db_sling_test`.`customer_tmp` does not exist
2024-02-28 19:16:38 DBG create table if not exists `db_sling_test`.`customer_tmp` (`c_custkey` bigint,
`c_name` varchar(65533),
`c_address` varchar(65533),
`c_city` varchar(65533),
`c_nation` varchar(65533),
`c_region` varchar(65533),
`c_phone` varchar(65533),
`c_mktsegment` varchar(65533),
`_sling_row_id` varchar(65533))  distributed by hash(`_sling_row_id`)
2024-02-28 19:16:38 INF execution failed
fatal:
~ execution failed
--- task_run.go:98 func1 ---
~ Could not WriteToDb
--- task_run.go:520 runDbToDb ---
~ could not create temp table `db_sling_test`.`customer_tmp`
--- task_run_write.go:190 WriteToDb ---
~ Error creating table `db_sling_test`.`customer_tmp`
--- task_func.go:73 createTableIfNotExists ---
~ Could not execute SQL
--- database.go:1161 ExecMulti ---

--- task_run.go:98 func1 ---
--- task_run.go:520 runDbToDb ---
--- task_run_write.go:190 WriteToDb ---
--- task_func.go:73 createTableIfNotExists ---
--- database.go:1159 ExecMulti ---
~ Error executing query
--- database.go:1198 ExecMultiContext ---
~ Error executing [tx: false] create table if not exists `db_sling_test`.`customer_tmp` (`c_custkey` bigint,
`c_name` varchar(65533),
`c_address` varchar(65533),
`c_city` varchar(65533),
`c_nation` varchar(65533),
`c_region` varchar(65533),
`c_phone` varchar(65533),
`c_mktsegment` varchar(65533),
`_sling_row_id` varchar(65533))  distributed by hash(`_sling_row_id`)
--- database.go:1185 ExecContext ---
Error 1064 (HY000):  Getting analyzing error. Detail message: Unknown database 'db_sling_test'.
wangyouzhuo@markovwong file %

**Comment by flarco** [comment] 2024-02-28 11:19
in your starrocks db, what is the output of `show databases`?

**Comment by MarkovWangRR** [comment] 2024-02-28 11:20
In fact, there is an existing database named 'DB_SLING_TEST' in StarRocks that i create before. But 'db_sling_test' is not existing in StarRocks.


<img width="883" alt="截屏2024-02-28 19 19 11" src="https://github.com/slingdata-io/sling-cli/assets/101642945/4ab9cf05-785a-44e4-8243-005e19e40692">

**Comment by MarkovWangRR** [comment] 2024-02-28 11:25
I can share my snowflake DDL with you. I don't whether it will be helpful for this issues.

create or replace TABLE STARROCK_TEST_DATA.SSB_SF100GCL.CUSTOMER cluster by (c_custkey)
(
	C_CUSTKEY NUMBER(38,0) NOT NULL,
	C_NAME VARCHAR(26) NOT NULL,
	C_ADDRESS VARCHAR(41) NOT NULL,
	C_CITY VARCHAR(11) NOT NULL,
	C_NATION VARCHAR(16) NOT NULL,
	C_REGION VARCHAR(13) NOT NULL,
	C_PHONE VARCHAR(16) NOT NULL,
	C_MKTSEGMENT VARCHAR(11) NOT NULL
);

**Comment by MarkovWangRR** [comment] 2024-02-28 11:27
This the the test data for  snowflake table STARROCK_TEST_DATA.SSB_SF100GCL.CUSTOMER

[Uploading snowflake_customer_1.csv…]()

**Comment by flarco** [comment] 2024-02-28 11:46
Thanks, I was able to reproduce.
Simple fix [here](https://github.com/slingdata-io/sling-cli/pull/191/commits/a0cbe12fc00bd813a07291b24e69e526aae1730d)!
Closing, will release v1.1.9 once I get those [tests](https://github.com/slingdata-io/sling-cli/actions/workflows/build-test.yml) to pass 😄 .

**Closed by flarco** 2024-02-28 11:46 UTC

**Comment by MarkovWangRR** [comment] 2024-02-28 11:48
So quickily fixing! Amazing!
