### ISSUE TITLE
SQL SERVER regression due to issue 402

### ISSUE THREAD

**Issue by CharlesRngrd** [slingdata-io/sling-cli#415] opened 2024-10-22 08:49 UTC
- Description of the issue: 

The fix for https://github.com/slingdata-io/sling-cli/issues/402 introduced a regression for me.

It seems that if the SQL Server is configured to use SQL Server authentication instead of Windows authentication, the `-T` flag won’t work.

As I'm using a service account that is not linked to the Active Directory plus the server instance is on-premise, I must use trust the server certificate plus send the credentials to BCP.

Instead of the `isTrusted` function, I suggest to add a `isBulkTrusted` connection parameter.

Ok for you @flarco and @pSpitzner ?

- Sling version:

`1.2.21`

- Operating System:

`Window`

- Connection Configuration: 

```yaml
connections:
  datalake_prod:
    type: sqlserver
    host: dlprod.cofaq.fr
    user: service-databi
    password: ****
    database: SLING
    port: 31435
    trust_server_certificate: true
```
- Log Output : 

```
~ could not bulk import
~ SQL Server BCP Import Command -> bcp 'dbo.BRAINDBM_BASEREF__conditions_tmp' in 'C:/Users/apautrot/AppData/Local/Temp/sqlserver.1729586398168.YlM1.csv' -S '****' -d 'SLING' -t ',' -m '1' '-w' -q -b '50000' -F '2' -e 'C:/Users/apautrot/AppData/Local/Temp/sqlserver.1729586398412.Epd.error' '-T'
SQL Server BCP Import Error  ->
SQLState = 28000, NativeError = 18452
Error = [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed. The login is from an untrusted domain and cannot be used with Integrated authentication.
```

**Comment by flarco** [comment] 2024-10-22 09:09
Ah OK, I think [this commit](https://github.com/slingdata-io/sling-cli/pull/410/commits/cbdb72fc861805c68cdf920e6a68548c9fb2b18f) will do the trick.

Right now, the `isTrusted` function returns `true` if the `TrustServerCertificate` or `TrustedConnection` is set to `true`.
New logic will use `-T` only for `TrustedConnection`.

Can you test with the latest [dev build](https://github.com/slingdata-io/sling-cli?tab=readme-ov-file#automated-dev-builds)? FYI @pSpitzner

**Comment by pSpitzner** [comment] 2024-10-23 05:25
I can confirm that the new dev build still works in my setup.
Tested with and without the extra `TrustServerCertificate=True`.

Also providing user login and pass worked with either or both options, `TrustServerCertificate` - and redundantly - `TrustedConnection`.

When giving user/pass and  `TrustedConnection`, the `-T` arg took precedence. Seems okay to me, since this is an inconsistent config anyway.

**Comment by flarco** [comment] 2024-10-23 09:24
Sounds good. For flexibility, there is also the `bcp_auth_string ` override parameter (which was undocumented), which allows you to provide custom BCP flags.
See [here](https://docs.slingdata.io/connections/database-connections/sqlserver#additional-parameters) for details.
Closing.

**Closed by flarco** 2024-10-23 09:24 UTC
Labels: bug
