### ISSUE TITLE
ClickHouse source incremental mode fails with `clickhouse does not recognize '2024-01-20 12:38:00.000' as DateTime value`

### ISSUE THREAD

**Issue by kmamykin** [slingdata-io/sling-cli#126] opened 2024-01-20 14:59 UTC
Here is my task config:

```
source:
  conn: clickhouse
  stream: common.my_table
  update_key: updated
target:
  conn: snowflake
  object: sling.my_table
mode: incremental
```

The first run replicates table fine, but the second incremental run fails:

```
sling run -d -c sling/my_table.yaml 
2024-01-20 14:49:02 DBG Sling version: 1.0.70 (linux amd64)
2024-01-20 14:49:02 DBG type is db-db
2024-01-20 14:49:02 DBG using source options: {"empty_as_null":true,"null_if":"NULL","datetime_format":"AUTO","max_decimals":-1}
2024-01-20 14:49:02 DBG using target options: {"datetime_format":"auto","max_decimals":-1,"use_bulk":true,"add_new_columns":true,"column_casing":"source"}
2024-01-20 14:49:02 INF connecting to source database (clickhouse)
2024-01-20 14:49:02 INF connecting to target database (snowflake)
2024-01-20 14:49:02 INF getting checkpoint value
2024-01-20 14:49:02 DBG select max("UPDATED") as max_val from "SLING"."MY_TABLE"
2024-01-20 14:49:02 INF reading from source database
2024-01-20 14:49:02 DBG select * from `common`.`my_table` where `updated` > '2024-01-20 13:38:07.000' order by `updated` asc 
2024-01-20 14:49:03 INF execution failed

fatal:
~ execution failed
--- task_run.go:88 func1 ---
~ Could not ReadFromDB
--- task_run.go:620 runDbToDb ---
~ Could not BulkExportFlow: select * from `common`.`my_table` where `updated` > '2024-01-20 13:38:07.000' order by `updated` asc 
--- task_run_read.go:170 ReadFromDB ---
--- database.go:2418 func1 ---
--- database.go:841 BulkExportStream ---
~ Error running query
--- database.go:852 StreamRows ---
~ SQL Error for:
select * from `common`.`my_table` where `updated` > '2024-01-20 13:38:07.000' order by `updated` asc 
--- database.go:890 StreamRowsContext ---
code: 53, message: Cannot convert string 2024-01-20 13:38:07.000 to type DateTime: while executing 'FUNCTION greater(updated : 0, '2024-01-20 13:38:07.000' : 1) -> greater(updated, '2024-01-20 13:38:07.000') UInt8 : 2'

context canceled
```

In ClickHouse `my_table` is defined as:

```
CREATE TABLE my_table (
    ...
    `updated`                   DateTime DEFAULT now()
)
ENGINE = ReplacingMergeTree(updated)
```

ClickHouse's `DateTime` type has only seconds precision, and even `select toDateTime('2024-01-20 13:38:07.000')` fails.

However  both statements succeed if milliseconds are removed: 
```
select toDateTime('2024-01-20 13:38:07');
select * from `common`.`grid_iso_predictions` where `updated` > '2024-01-20 13:38:07' order by `updated` asc;
```

Is there a way to configure this behavior?

**Comment by flarco** [comment] 2024-01-20 16:16
That's a bug, thanks for reporting.
Fixed in #127, it will show as `select * from common.my_table where updated > parseDateTime64BestEffortOrNull'2024-01-20 13:38:07.000') order by updated asc`

**Comment by flarco** [comment] 2024-01-20 17:03
Released `v1.0.71`. Closing

**Closed by flarco** 2024-01-20 17:03 UTC
Labels: bug

**Comment by kmamykin** [comment] 2024-01-20 17:46
What I see is the logs is that the query to fetch the updates is:
```
select * from `common`.`my_table` where `updated` >= parseDateTime64BestEffortOrNull('2024-01-20 17:34:43.000000 +00') order by `updated` asc
```
Note the `>=`. It's causing the query to always return some rows (even though there have not been any updates to the source table), since we are comparing to the max(updated) in the target table.

**Comment by flarco** [comment] 2024-01-20 17:56
Yes, it's by design, see comments here: https://github.com/slingdata-io/sling-cli/blob/main/core/sling/task_run_read.go#L70-L73
