### ISSUE TITLE
Filtering stream name by pattern not matching file extension

### ISSUE THREAD

**Issue by guaripete-github** [slingdata-io/sling-cli#406] opened 2024-10-17 15:08 UTC
## Issue Description

- Description of the issue: In a folder with mixed files (e.g., csv and xlsx), defining a stream with pattern *.csv captures both .csv and .xlsx files

- Sling version (`sling --version`): 1.2.20

- Operating System (`linux`, `mac`, `windows`): windows

- Replication Configuration: 

```ps
sling conns discover LOCAL --pattern "file://C:/Test/*.csv"
```

- Log Output (please run command with `-d`): 

```
DBG opened "file" connection (conn-file-fDr)
DBG file discover inputs: {"column_level":"","pattern":"file://C:/Test/*.csv","recursive":false,"url":"file://C:/Test/"}
DBG unfiltered nodes returned: 2
DBG ["C:/Test/New Microsoft Excel Worksheet.xlsx","C:/Test/New Text Document.csv"]
INF no result.
```

**Comment by flarco** [comment] 2024-10-19 01:16
@guaripete-github  I think it's working as intended.
`sling conns discover local` actually doesn't like the `file://` prefix for `--pattern`. 
I tried on my machine with `file://` and without. Without worked.
I'll add a trim logic for that. Closing, feel free to reopen.

**Closed by flarco** 2024-10-19 01:16 UTC
