### ISSUE TITLE
Iceberg support

### ISSUE THREAD

**Issue by toddy86** [slingdata-io/sling-cli#81] opened 2023-12-05 16:54 UTC
Hi, 

Are there any considerations to add Apache Iceberg as a destination table format (on S3, GCS etc)?

Similar to the request that I've seen for Delta [here](https://github.com/slingdata-io/sling-cli/issues/26)

All the best

Todd

**Comment by flarco** [comment] 2023-12-06 10:48
Thanks, adding some links:
- https://github.com/apache/iceberg-go
- https://pkg.go.dev/github.com/apache/arrow/go/v14@v14.0.0
- https://github.com/apache/arrow/tree/main/go

**Comment by alberttwong** [comment] 2024-02-09 17:35
The easiest way may be to use DuckDB with Iceberg and executing it behind the scenes.  https://duckdb.org/docs/extensions/iceberg.html

**Comment by parsingeye** [comment] 2024-03-05 13:33
Alternatively, iceberg support can be achieved through AWS Athena support, the way `dtl` supports it https://dlthub.com/docs/dlt-ecosystem/destinations/athena#additional-destination-options

**Comment by alberttwong** [comment] 2024-03-28 17:05
The problem is that it's not enough to support iceberg format.  You also need to register those files/data into HMS so that projects like Trino and StarRocks can be a SQL query engine to the data within those formats.

**Comment by flarco** [comment] 2024-08-28 11:53
Added in #357 

See https://blog.slingdata.io/reading-apache-iceberg-data-with-sling

Closing.

**Closed by flarco** 2024-08-28 11:53 UTC
Labels: enhancement, external
