### ISSUE TITLE
Panic while exporting Trino table to local parquet file

### ISSUE THREAD

**Issue by jhatcher1** [slingdata-io/sling-cli#298] opened 2024-05-16 18:09 UTC
Hello! I'm a new user of sling, thanks for the project!

## Issue Description

- Description of the issue: 
When running a command like: `sling run --src-conn TRINO --src-stream "myschema.mytable" --tgt-object "file:///tmp/mytable.parquet"` I am getting a panic.

  The stack trace is quite big, so I've attached it in a file here: 
[sling_panic.txt](https://github.com/slingdata-io/sling-cli/files/15338986/sling_panic.txt)

  I'm not seeing this issue for all tables I try to export to parquet, but for the tables where I do see this issue, I'm encountering it consistently. I'm able to export these tables to CSV without any issue. The tables I'm encountering this issue with aren't very complicated - they have a bigint column, ~7 integer columns, and ~30 boolean columns.

- Sling version (`sling --version`): v1.2.9

- Operating System (`linux`, `mac`, `windows`): Mac (Arm)

- Replication Configuration: 
```
sling conns set TRINO type=trino http_url="http://admin@localhost:8888?catalog=iceberg&schema=myschema"
```

- Log Output (please run command with `-d`): 

```
$ sling run --src-conn TRINO --src-stream "myschema.mytable" --tgt-object "file:///tmp/mytable.parquet" -d
2024-05-16 13:55:17 DBG Sling version: 1.2.9 (darwin arm64)
2024-05-16 13:55:17 DBG type is db-file
2024-05-16 13:55:17 DBG using source options: {"empty_as_null":false,"null_if":"NULL","datetime_format":"AUTO","max_decimals":-1}
2024-05-16 13:55:17 DBG using target options: {"header":true,"compression":"AUTO","concurrency":7,"datetime_format":"auto","delimiter":",","max_decimals":-1,"use_bulk":true,"add_new_columns":true,"column_casing":"source"}
2024-05-16 13:55:17 INF connecting to source database (trino)
2024-05-16 13:55:17 DBG opened "trino" connection (conn-trino-CaP)
2024-05-16 13:55:17 INF reading from source database
2024-05-16 13:55:17 DBG select * from "myschema"."mytable"
2024-05-16 13:55:17 INF writing to target file system (file)
2024-05-16 13:55:17 DBG writing to file:///tmp/mytable.parquet [fileRowLimit=0 fileBytesLimit=0 compression=AUTO concurrency=7 useBufferedStream=false fileFormat=parquet]
runtime: bad pointer in frame github.com/flarco/g/csv.(*Writer).Write at 0x14001931e80: 0x1
fatal error: invalid pointer found on stack

...

Same stack trace as above
```

**Comment by flarco** [comment] 2024-05-16 18:33
Thanks for reporting, those are hard to debug because I can't reproduce.
If you run with env var `SLING_PROCESS_BW=false`, I think it should work. It's erroring when sling try to determine how many bytes have been written (for some specific row).

**Comment by flarco** [comment] 2024-05-22 13:20
Closing this. Feel free to re-open.

**Closed by flarco** 2024-05-22 13:20 UTC

**Comment by jhatcher1** [comment] 2024-05-23 14:37
Running sling with `SLING_PROCESS_BW=false` worked for me. If I can figure out how to reproduce the issue, I'll reopen this with more info. Thanks!
