### ISSUE TITLE
S3 to Snowflake: Non-deterministic number of records streaming from folder of JSON files

### ISSUE THREAD

**Issue by nicklausroach** [slingdata-io/sling-cli#101] opened 2024-01-08 20:34 UTC
When attempting to stream a folder of JSON files from S3 to Snowflake, a seemingly random, small subset of records are streamed while the rest are not. 

Task yaml:

```
source:
  conn: AWS_S3
  stream: /entries/
  primary_key: [id]
  update_key: date
  options:
    format: json
    flatten: true


target:
  conn: SNOWFLAKE
  object: load.entries
  options:
    column_casing: snake

mode: full-refresh
```

Running `sling run -c task.yaml` will stream anywhere from 30 to 150 of the 4000 records in the directory with seemingly no overt failure message.

The data are JSON files with file name YYYY-MM-DD.json for every day from 2023-10-19 to today. 

General format of the JSON data:
```
[
    {
        "Id": 295,
        "Name": "Description of some event",
        "Type": "VideoPlaybackStopped",
        "Date": "2023-10-28T20:42:21.8815348Z",
        "UserId": "cacd28457c174151ba6133b11ecd6008",
        "Severity": "Information"
    },
    {
        "Id": 294,
        "Name": "Description of some other event,
        "Type": "VideoPlayback",
        "Date": "2023-10-28T20:26:29.2277072Z",
        "UserId": "cacd28457c174151ba6133b11ecd6008",
        "Severity": "Information"
    },
]
```

There are some events that include a "shortOverview" field that usually just includes an IP address when the field is present.

[Results of a task run with debug flag.](https://github.com/slingdata-io/sling-cli/files/13866051/debug.txt)

**Comment by nicklausroach** [comment] 2024-01-08 20:40
Also worth noting that streaming individual files in the directory works as expected.

**Comment by flarco** [comment] 2024-01-08 21:59
@nicklausroach what version of sling are you using?

**Comment by nicklausroach** [comment] 2024-01-08 22:05
@flarco 1.0.66

**Comment by nicklausroach** [comment] 2024-01-08 23:19
Also, it seems like only dates up to 2023-11-22 are being processed.

**Comment by flarco** [comment] 2024-01-08 23:43
I am unable to reproduce. I copied a couple of records over and over in one file, totaling up to 4112 records in a file, and created 100 identical JSON files. Copied them to a folder in my AWS S3 bucket. Each time I run, sling processes 100 files / 412200 records perfectly using the same config you provided.

🤔 

What machine are you using to run? how many cores?
Can you set env var `CONCURENCY_LIMIT=10` and try again?

**Comment by nicklausroach** [comment] 2024-01-09 00:56
@flarco that's so strange!

I tried this on both my local M1 Mac and a remote EC2 instance, same issue on both. Would it help if I briefly made the bucket public and gave you the path to try this on? I'm not worried about any sensitive info in there.

**Comment by flarco** [comment] 2024-01-09 01:35
@nicklausroach sure, sounds good.

**Comment by flarco** [comment] 2024-01-09 11:07
Got it: https://github.com/flarco/dbio/commit/f1f536c81b6b01109009a81d454f10d319a4d3cd
We should be good! Record count is consistent now. Thanks for raising this.
Will be released when #99 is merged.

**Closed by flarco** 2024-01-09 11:07 UTC
Labels: bug

**Comment by nicklausroach** [comment] 2024-01-09 15:01
@flarco really appreciate the quick turnaround on this. Thanks so much!

**Comment by flarco** [comment] 2024-01-10 00:51
v1.0.68 Released.
