### ISSUE TITLE
Bug with loading Clickhouse array columns to Snowflake

### ISSUE THREAD

**Issue by axelwas** [slingdata-io/sling-cli#118] opened 2024-01-12 17:07 UTC
After successfully connecting to Clickhouse thanks to your previous enhancement, I tried to load parts of a big table using an incremental/custom SQL sync to Snowflake and encountered an issue.

In the source table, there is json/object data stored across multiple array columns that have `.` in their name.
For example for a `car_dealerships` table containing inventories, we'd have array columns `cars.serial_number`, `cars.name`, `cars.model`.

Sling creates the Snowflake tmp table keeping the source table column names as they are with the `.`.
It then executes the query and serializes the result into multiple csv files where `.` in column names are replaced with `_`.

However, when Sling generates the `copy into` statement to load from the staged csv to the tmp table, only the part of the column name after `.` is used (ex: `serial_number` for source column `cars.serial_number`).
As a result it throws "invalid identifier `serial_number`".

I think this is due to the behaviour of [ParseColumnName](https://github.com/flarco/dbio/blob/main/database/schemata.go#L361) function, used in [CopyViaStage](https://github.com/flarco/dbio/blob/f1fc07880e938642c153e8cc91980f30a2a9ffa0/database/database_snowflake.go#L596C28-L596C40) method.

On another topic, I see the tmp table created uses `text` for array columns. Do you plan to add support for array/map datatypes in the future ?

**Comment by flarco** [comment] 2024-01-12 18:03
Ah ok.

- Could you attach the full log output using the debug flag (`-d`)? Will help me see what’s going on.
- Also, the DDL of the source table and example values of the array columns will be helpful.

For your last question, will fix, didn’t realized it was mapped to `text`, should be mapped to `json`.
Mapping file is [here](https://github.com/flarco/dbio/blob/main/database/templates/types_native_to_general.tsv).

**Comment by axelwas** [comment] 2024-01-12 19:51
Sure, to simplify the log output, I retried with a subset of columns.

execution log:
```
2024-01-12 20:39:04 DBG Sling version: dev (darwin arm64)
2024-01-12 20:39:04 DBG type is db-db
2024-01-12 20:39:04 DBG using source options: {"empty_as_null":true,"null_if":"NULL","datetime_format":"AUTO","max_decimals":-1,"limit":10000}
2024-01-12 20:39:04 DBG using target options: {"datetime_format":"auto","max_decimals":-1,"use_bulk":true,"add_new_columns":true,"column_casing":"source"}
2024-01-12 20:39:04 INF connecting to source database (clickhouse)
2024-01-12 20:39:05 INF connecting to target database (snowflake)
2024-01-12 20:39:05 INF getting checkpoint value
2024-01-12 20:39:05 DBG select max("last_enriched_at") as max_val from "CLICKHOUSE"."VIEWS_SLING"
2024-01-12 20:39:06 INF reading from source database
2024-01-12 20:39:06 DBG select
view_id,
errors.error_type,
errors.error_time,
dynamic_vars_string_in_session.key,
dynamic_vars_string_in_session.value,
dynamic_vars_int_in_session.key,
dynamic_vars_int_in_session.value
from views final
where 1=1
and session_date >= coalesce(addDays(toDate(null),-8), '2024-01-10')
and last_enriched_at > coalesce(null, '2024-01-12 00:00:00')
2024-01-12 20:39:22 INF writing to target database [mode: incremental]
2024-01-12 20:39:22 DBG drop table if exists "CLICKHOUSE"."VIEWS_SLING_TMP"
2024-01-12 20:39:22 DBG table "CLICKHOUSE"."VIEWS_SLING_TMP" dropped
2024-01-12 20:39:23 DBG create table "CLICKHOUSE"."VIEWS_SLING_TMP" ("VIEW_ID" bigint,
"ERRORS.ERROR_TYPE" text,
"ERRORS.ERROR_TIME" text,
"DYNAMIC_VARS_STRING_IN_SESSION.KEY" text,
"DYNAMIC_VARS_STRING_IN_SESSION.VALUE" text,
"DYNAMIC_VARS_INT_IN_SESSION.KEY" text,
"DYNAMIC_VARS_INT_IN_SESSION.VALUE" text,
"_SLING_LOADED_AT" integer)
2024-01-12 20:39:23 INF streaming data
2024-01-12 20:39:23 DBG USE SCHEMA CLICKHOUSE
2024-01-12 20:39:23 DBG writing to /var/folders/0h/b3668srs6bl9mk00gm5td7r00000gq/T/snowflake/put/2024-01-12T203923.436/part.01 [fileRowLimit=500000 fileBytesLimit=96000000 compression=ZSTD concurrency=7 useBufferedStream=false fileFormat=csv]
2024-01-12 20:39:23 DBG REMOVE @CLICKHOUSE.sling_staging/"CLICKHOUSE"."VIEWS_SLING_TMP"/2024-01-12T203923.436
1s 27,859 ? p/s  | 0 B/s | 62% MEM | 18% CPU 2024-01-12 20:39:25 DBG PUT 'file:///var/folders/0h/b3668srs6bl9mk00gm5td7r00000gq/T/snowflake/put/2024-01-12T203923.436/part.01.0001.csv.zst' @CLICKHOUSE.sling_staging/"CLICKHOUSE"."VIEWS_SLING_TMP"/2024-01-12T203923.436 PARALLEL=1 AUTO_COMPRESS=FALSE
3s 141,037 69403 r/s  | 0 B/s | 62% MEM | 19% CPU 2024-01-12 20:39:27 DBG COPY INTO "CLICKHOUSE"."VIEWS_SLING_TMP" ("VIEW_ID", "ERROR_TYPE", "ERROR_TIME", "KEY", "VALUE", "KEY", "VALUE", "_SLING_LOADED_AT")
FROM (
  SELECT T.$1, T.$2, T.$3, T.$4, T.$5, T.$6, T.$7, T.$8
  FROM @CLICKHOUSE.sling_staging/"CLICKHOUSE"."VIEWS_SLING_TMP"/2024-01-12T203923.436/part.01.0001.csv.zst as T
)
FILE_FORMAT = (
  TYPE = CSV
  RECORD_DELIMITER = '\n'
  ESCAPE_UNENCLOSED_FIELD = NONE
  FIELD_OPTIONALLY_ENCLOSED_BY='0x22'
  EMPTY_FIELD_AS_NULL=TRUE
  NULL_IF = ''
  SKIP_HEADER=1
  REPLACE_INVALID_CHARACTERS=TRUE
)
ON_ERROR = ABORT_STATEMENT

2024-01-12 20:39:27 DBG REMOVE @CLICKHOUSE.sling_staging/"CLICKHOUSE"."VIEWS_SLING_TMP"/2024-01-12T203923.436
4s 141,037 49846 r/s  | 0 B/s | 62% MEM | 21% CPU
2024-01-12 20:39:27 DBG connection was closed, reconnecting
2024-01-12 20:39:28 DBG drop table if exists "CLICKHOUSE"."VIEWS_SLING_TMP"
2024-01-12 20:39:28 DBG table "CLICKHOUSE"."VIEWS_SLING_TMP" dropped
2024-01-12 20:39:28 INF execution failed
fatal:
--- sling.go:421 func1 ---
--- sling.go:462 cliInit ---
--- cli.go:283 CliProcess ---
~ failure running task (see docs @ https://docs.slingdata.io/sling-cli)
--- sling_logic.go:191 processRun ---
--- sling_logic.go:286 runTask ---
~ execution failed
--- task_run.go:131 Execute ---
--- task_run.go:88 func1 ---
--- task_run.go:638 runDbToDb ---
--- task_run_write.go:250 WriteToDb ---
~ Could not WriteToDb
--- database_snowflake.go:358 BulkImportFlow ---
~ could not insert into "CLICKHOUSE"."VIEWS_SLING"
--- database_snowflake.go:702 CopyViaStage ---
context canceled

~ Error with COPY INTO
--- database_snowflake.go:687 func5 ---
~ Could not execute SQL
--- database.go:1108 Exec ---
~ Error executing query [tx: true]
--- database.go:1141 ExecContext ---
~ Error executing COPY INTO "CLICKHOUSE"."VIEWS_SLING_TMP" ("VIEW_ID", "ERROR_TYPE", "ERROR_TIME", "KEY", "VALUE", "KEY", "VALUE", "_SLING_LOADED_AT")
FROM (
  SELECT T.$1, T.$2, T.$3, T.$4, T.$5, T.$6, T.$7, T.$8
  FROM @CLICKHOUSE.sling_staging/"CLICKHOUSE"."VIEWS_SLING_TMP"/2024-01-12T203923.436/part.01.0001.csv.zst as T
)
FILE_FORMAT = (
  TYPE = CSV
  RECORD_DELIMITER = '\n'
  ESCAPE_UNENCLOSED_FIELD = NONE
  FIELD_OPTIONALLY_ENCLOSED_BY='0x22'
  EMPTY_FIELD_AS_NULL=TRUE
  NULL_IF = ''
  SKIP_HEADER=1
  REPLACE_INVALID_CHARACTERS=TRUE
)
ON_ERROR = ABORT_STATEMENT

--- transaction.go:139 ExecContext ---
000904 (42000): SQL compilation error: error line 1 at position 53
invalid identifier 'ERROR_TYPE'

context canceled

~ Error with COPY INTO
--- database_snowflake.go:687 func5 ---
~ Could not execute SQL
--- database.go:1108 Exec ---
~ Error executing query [tx: true]
--- database.go:1141 ExecContext ---
~ Error executing COPY INTO "CLICKHOUSE"."VIEWS_SLING_TMP" ("VIEW_ID", "ERROR_TYPE", "ERROR_TIME", "KEY", "VALUE", "KEY", "VALUE", "_SLING_LOADED_AT")
FROM (
  SELECT T.$1, T.$2, T.$3, T.$4, T.$5, T.$6, T.$7, T.$8
  FROM @CLICKHOUSE.sling_staging/"CLICKHOUSE"."VIEWS_SLING_TMP"/2024-01-12T203923.436/part.01.0001.csv.zst as T
)
FILE_FORMAT = (
  TYPE = CSV
  RECORD_DELIMITER = '\n'
  ESCAPE_UNENCLOSED_FIELD = NONE
  FIELD_OPTIONALLY_ENCLOSED_BY='0x22'
  EMPTY_FIELD_AS_NULL=TRUE
  NULL_IF = ''
  SKIP_HEADER=1
  REPLACE_INVALID_CHARACTERS=TRUE
)
ON_ERROR = ABORT_STATEMENT

--- transaction.go:139 ExecContext ---
000904 (42000): SQL compilation error: error line 1 at position 53
invalid identifier 'ERROR_TYPE'
```

(partial) source table DDL:
```
create table views (
    view_id UInt64
    `dynamic_vars_string_in_session.key` Array(String),
    `dynamic_vars_string_in_session.value` Array(String),
    `dynamic_vars_int_in_session.key` Array(String),
    `dynamic_vars_int_in_session.value` Array(UInt32),
    `errors.error_type` Array(LowCardinality(String)),
    `errors.error_time` Array(DateTime),
```

**Comment by axelwas** [comment] 2024-01-12 19:52
I also noticed the `limit` param doesn't seem to be effective as I don't see it in the generated Clickhouse query.

**Comment by flarco** [comment] 2024-01-12 20:01
> I also noticed the limit param doesn't seem to be effective as I don't see it in the generated Clickhouse query.
Ah yea, it's cause you're using a custom sql. Will take a look.

**Comment by flarco** [comment] 2024-01-12 20:07
Those are strange column names:

```sql
create table "CLICKHOUSE"."VIEWS_SLING_TMP" ("VIEW_ID" bigint,
"ERRORS.ERROR_TYPE" text,
"ERRORS.ERROR_TIME" text,
"DYNAMIC_VARS_STRING_IN_SESSION.KEY" text,
"DYNAMIC_VARS_STRING_IN_SESSION.VALUE" text,
"DYNAMIC_VARS_INT_IN_SESSION.KEY" text,
"DYNAMIC_VARS_INT_IN_SESSION.VALUE" text,
"_SLING_LOADED_AT" integer)
```

Sling uses the column name returned by the CH driver, it's strange that the resultset columns are `ERRORS.ERROR_TYPE` and `ERRORS.ERROR_TIME`. Can you try adding aliases? like `errors.error_type as error_type, errors.error_time as error_time,` can confirm that works?
I don't think it was like this, I just upgraded the CH driver in last release, that might have messed it up. Will take a look.

**Comment by flarco** [comment] 2024-01-12 20:24
I just updated the array type mapping in branch `v1.0.70`, can you test?

**Comment by axelwas** [comment] 2024-01-12 20:57
Hi,

- Yes it does work when I alias the columns. Though it is expected that column names returned by the CH driver contain dots as it is how nested data structures are handled in CH as mentioned [here](https://clickhouse.com/docs/en/sql-reference/data-types/nested-data-structures/nested#:~:text=In%20most%20cases%2C%20when%20working,structure%20have%20the%20same%20length.).
- With v1.0.70 array columns are created as variants in the tmp/target Snowflake tables. Unfortunately, wether I use v1.0.69 (varchar) or 1.0.70 (variant), all array column values are null.

**Comment by flarco** [comment] 2024-01-12 21:06
Thanks, will look into it.

**Comment by axelwas** [comment] 2024-01-12 21:09
Thanks !

**Comment by axelwas** [comment] 2024-01-12 21:52
I downloaded the staged csv file and indeed array values are empty.

I also noticed UInt64 values are incorrectly serialized as Int64 because many values are negative for view_id in the csv. In the mapping file, it's correctly mapped to bigint but I found an occurrence of bigint being casted to Int64 in [stream_processor](https://github.com/flarco/dbio/blob/832c81069bc91bac4da7559b0efeddbb43986489/iop/stream_processor.go#L670C27-L670C27), hence the negative value I guess ?

**Comment by flarco** [comment] 2024-01-17 11:38
@axelwas OK, made some changes and seems to be working now. The thing was that clickhouse driver is converting the values into native Go Slices. So it wasn't getting converted into a json string properly. Added this [commit](https://github.com/flarco/dbio/commit/f615d02c499e76d6b0b755030d4f9eb97363de50#diff-85f20c1b2eaf19cc262bf34fc4b220a11a3a84c1ac96aeb699923856b75bcc57R423-R427) to handle those.

Also for the uint64, I changed the general mapping from `bigint` into `decimal`. See commit [here](https://github.com/flarco/dbio/commit/0e8d1dbab8bd75ccf0614b70e100f3d0e0c75970). This should handle it better. In case you don't want the extra decimals inside of Snowflake, I'd suggest you use the `source.options.columns` to cast as `view_id` as string (or do that in your custom sql), since there is no uint64 in snowflake, and those really large numbers can give issues. Another is to create your ddl with `NUMBER(20)` or something inside of snowflake, and using the `truncate` or `incremental` mode so the DDL is kept intact.

Can you test and let me know how that goes?

**Comment by flarco** [comment] 2024-01-23 13:28
Closing for now. Re-open if issue persists.

**Closed by flarco** 2024-01-23 13:28 UTC
Labels: bug, enhancement

**Comment by axelwas** [comment] 2024-01-23 14:18
@flarco I confirm the array bug is fixed, thanks !

As you expected it's not totally for Uint64 as the auto generated Snowflake DDL has Uint64 columns created as `DECIMAL(24,9)`. 24 is the total number of digits, including up to 9 after floating point, so max int value allowed is 10e16-1 while max Uint64 value has 20 digits. Having dbio to create it as `DECIMAL(38,9)` instead would solve the issue.

**Comment by axelwas** [comment] 2024-01-23 14:19
I will try the different options you suggested to handle it

**Comment by flarco** [comment] 2024-01-23 14:24
can you try `source.options.columns: { my_uint64_col: 'decimal(38,9)' }`? sling should now parse the `(38,9)` part.
See https://github.com/slingdata-io/sling-cli/blob/main/core/sling/task.go#L351-L386

**Comment by flarco** [comment] 2024-01-23 14:25
I'll see if it's feasible default to `decimal(38,9)` in the mapping 👍

**Comment by axelwas** [comment] 2024-01-26 15:14
Hi @flarco,

Following up on this topic (let me know if you want me to create separate issues :

- Using  `source.options.columns: { my_uint64_col: 'decimal(38,9)' }` works, even better with `decimal(38,0)` (so I don't have a bunch of 0s on display when I query). However, using `bigint` casts the values to string. Is this expected behaviour ?
- There is an encoding issue affecting `Array(Uint8)` columns. The column is created as `varchar` instead of `variant` and values are wrongly encoded with non utf-8 chars.
- The type of `_sling_loaded_at` is `number` instead of `timestampntz`

**Comment by flarco** [comment] 2024-01-27 01:54
- using `bigint` shouldn't cast as string, unless the value is too large for Go's `in64` or `float64`. It should say in the log with debug whether it's casted to string, can you verify? Logic is [here](https://github.com/flarco/dbio/blob/main/iop/stream_processor.go#L499-L510).
- what is the encoding in the source? Could you try a [transform](https://github.com/slingdata-io/sling-cli/blob/main/core/sling/tranforms.go) like `decode_latin1`?
- yes, as designed, `_sling_loaded_at` is an [epoch timestamp value](https://www.epochconverter.com/).
